language: python
env:
  global:
  - HUGO_VERSION="0.31"
  - TRAVIS_NODE_VERSION="7"
before_install:
- openssl aes-256-cbc -K $encrypted_ba844ae62b2d_key -iv $encrypted_ba844ae62b2d_iv -in deploy-archifleks.github.io.key.enc -out deploy-archifleks.github.io.key -d
install:
- pip install ghp-import
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install --prefix static/resume
- rm -rf static/resume/node_modules/markdown-resume/assets/{css/*,templates/*}
- cp static/resume/resume.css static/resume/node_modules/markdown-resume/assets/css/.
- cp static/resume/default.html static/resume/node_modules/markdown-resume/assets/templates/.
script:
- static/resume/node_modules/markdown-resume/bin/md2resume static/resume/index.md
- wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | tar xvz
- ls
- ./hugo
- ghp-import public
branches:
  only:
  - master
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy-archifleks.github.io.key
- ssh-add deploy-archifleks.github.io.key
- git push -f git@github.com:archifleks/archifleks.github.io.git gh-pages:master
