language: python
env:
  global:
    - HUGO_VERSION=0.17
install:
  - pip install ghp-import
  - wget -qO- https://github.com/spf13/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.tar.gz | tar xvz
script:
  - chmod +x ./hugo_$HUGO_VERSION_linux_amd64
  - ./hugo_$HUGO_VERSION_linux_amd64
  - ghp-import public
branches:
  only:
    - master
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git push git@github.com:archifleks/archifleks.github.io.git gh-pages:master
